version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: wachtwoord-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wachtwoordengenerator
      MYSQL_USER: wachtwoord
      MYSQL_PASSWORD: Sterkwachtwoord
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - mysql
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  db_data: